listener 1883                                           #rimane in ascolto della porta 1883, devo collegare tutto su questa porta
allow_anonymous true                                    #per test lascio aperto
persistence true                                        #memorizzo su disco, nel caso si riavvia 
persistence_location /mosquitto/data/                   #gli dico dove salvare eventualmente
log_dest file /mosquitto/log/mosquitto.log              #scrive tutto su un file che posso controllare facilmente